### ISSUE TITLE
/serv-freeze crashes the server

### ISSUE THREAD

**Issue by Timoooo153** [QPCrummer/Slumber#4]
`/serv-freeze
[18:22:33] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_2168.method_9226(net.minecraft.class_2561, boolean)'
        at com.github.QPCrummer.slumber.ToggleCommand.lambda$register$1(ToggleCommand.java:23) ~[slumber-1.1.0.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_44252(class_2170.java:280) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zgc000$carpet$modifiedRunLoop(MinecraftServer.java:7942) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]`

**Comment by Ampflower** [comment]
Curious, which version of Minecraft are you using?

**Comment by GeraldTM** [comment]
encountering same issue, 1.20.1

**Comment by GeraldTM** [comment]
```
java.lang.NoSuchMethodError: 'void net.minecraft.class_2168.method_9226(net.minecraft.class_2561, boolean)'
	at com.github.QPCrummer.slumber.ToggleCommand.lambda$register$1(ToggleCommand.java:23) ~[slumber-1.1.0.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.method_44252(class_2170.java:280) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_13941(class_3176.java:299) ~[server-intermediary.jar:?]	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:284) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	at net.minecraft.server.MinecraftServer.handler$zga000$carpet$modifiedRunLoop(MinecraftServer.java:9442) ~[server-intermediary.jar:?]
```

**Comment by QPCrummer** [comment]
Ok, I’ll take a closer look at it this weekend. For now a dirty workaround is to just change “toggle” in the config assuming you aren’t frequently adjusting whether the mod is on or off.

**Comment by Timoooo153** [comment]
> Curious, which version of Minecraft are you using?

1.20.1 also

**Comment by QPCrummer** [comment]
@GeraldTM 
@Lequral 
The crash has been resolved in this version https://github.com/Tater-Certified/Slumber/releases/tag/1.1.1-1.20.1

Thanks for reporting the issue!
